### ISSUE TITLE
Feature Request: Improve search algorithm

### ISSUE THREAD

**Issue by narainkarthikv** [narainkarthikv/Nmoji#2]
We want to enhance the search functionality of the Nmoji application to make it more user-friendly and efficient. Currently, the search function works, but it can be improved in terms of speed and accuracy. This is a great opportunity for beginners to contribute to an open-source project and learn more about JavaScript and web development.

Task:

1. Improve the existing search algorithm to make it faster and more accurate.
2. Ensure that the search is case-insensitive.
3. Add a feature to highlight the matching text in the search results.

**Comment by PATILYASHH** [comment]
Hi , 

I am interested in this issue , can u assign me ?

**Comment by narainkarthikv** [comment]
Hey @PATILYASHH assigned it to you. Don't forget to add your name Contributors.md

**Comment by PATILYASHH** [comment]
> Hey @PATILYASHH assigned it to you. Don't forget to add your name Contributors.md

Hi @narainkarthikv,Thank you for assigning me to this issue. I have a few questions to ensure that I understand the changes you are looking for:Improving the Search Algorithm: Are there specific techniques or algorithms you have in mind to enhance the speed and accuracy of the search functionality? Also, could you specify the type of search algorithm you'd like to implement, similar to how Google search works on websites?Case-Insensitive Search: Should the case-insensitivity apply to all search inputs, or are there any exceptions?Highlighting Matching Text: Do you have a preferred style or format for highlighting the matching text in the search results?Looking forward to your input!Best regards,
Yash

**Comment by narainkarthikv** [comment]
Hi @PATILYASHH

- Improve the Search Algorithm:

1. Implement the debouncing method to improve the speed and accuracy of the search (as more emotes will be added in the future).
2. Ensure that the search is case-insensitive (it is already implemented, so leave this point).
3. If Possible, Add a button in the search bar to filter results based on tags and names.

- Enhance Data Consistency:

1. Standardize the data used for emotes, ensuring consistency in tags and names.

- Highlight Matching Text:

1. Add a feature to highlight the matching text in the emotes. (If searched heart, the heart based emotes should be highlighted with an unique color). (Consider this point optional).

Happy Contributing!

**Comment by PATILYASHH** [comment]
Got it 😁👍

**Comment by PATILYASHH** [comment]
I am having an issue with the emoji display on my forked repo. When I open `index.html` in VS Code, the emojis do not show. Is there any command I need to run to start the server properly? I have already checked that all dependencies are installed. Please advise on how to resolve this issue.

**Comment by DevyRuxpin** [comment]
I also had issues loading the emojis (.json). I rewrote the js code w the debounce function and added code to convert all to lowercase and set a timer to streamline the predictive text. I even used live server to localize the files and still haven't gotten the emojis to load.

**Comment by DevyRuxpin** [comment]
I wouldn't mind being assigned to this also, I am interested to see how others approached this as well, maybe collaborate.....

**Comment by DevyRuxpin** [comment]
document.addEventListener('DOMContentLoaded', () => {
    const filterInput = document.getElementById('filterInput');
    const emojiContainer = document.getElementById('emojiContainer');

    // Debounce function to limit rapid calls to filterEmojis
    function debounce(func, wait) {
        let timeout;
        return function executedFunction(...args) {
            const later = () => {
                clearTimeout(timeout);
                func(...args);
            };
            clearTimeout(timeout);
            timeout = setTimeout(later, wait);
        };
    }

    fetch('NmojiList.json')
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            return response.json();
        })
        .then(NmojiList => {
            displayEmojis(NmojiList);
            // Use debounce to improve performance
            filterInput.addEventListener('input', debounce(() => filterEmojis(NmojiList), 250));
        })
        .catch(error => {
            console.error('Error fetching the JSON data:', error);
        });

    function displayEmojis(emojis) {
        emojiContainer.innerHTML = '';
        emojis.forEach(emoji => {
            const emojiElement = document.createElement('div');
            emojiElement.classList.add('emoji');
            emojiElement.textContent = emoji.emoji;
            emojiElement.title = `${emoji.description} - Category: ${emoji.category}`;
            emojiElement.addEventListener('click', () => copyToClipboard(emoji.emoji));
            emojiContainer.appendChild(emojiElement);
        });
    }

    function filterEmojis(NmojiList) {
        const filterValue = filterInput.value.toLowerCase();
        const filteredEmojis = NmojiList.filter(emoji =>
            emoji.emoji.toLowerCase().includes(filterValue) ||
            emoji.description.toLowerCase().includes(filterValue) ||
            emoji.category.toLowerCase().includes(filterValue) ||
            (emoji.tags && emoji.tags.some(tag => tag.toLowerCase().includes(filterValue)))
        );
        displayEmojis(filteredEmojis);
    }

    function copyToClipboard(text) {
        if (navigator.clipboard) { // Modern async clipboard API
            navigator.clipboard.writeText(text).then(() => {
                console.log('Text copied to clipboard');
            }).catch(err => {
                console.error('Failed to copy text: ', err);
            });
        } else { // Fallback for older browsers
            const textArea = document.createElement('textarea');
            textArea.value = text;
            document.body.appendChild(textArea);
            textArea.focus();
            textArea.select();
            try {
                const successful = document.execCommand('copy');
                const msg = successful ? 'successful' : 'unsuccessful';
                console.log('Fallback: Copying text command was ' + msg);
            } catch (err) {
                console.error('Fallback: Oops, unable to copy', err);
            }
            document.body.removeChild(textArea);
        }
    }
});



//The fetch method is failing for me regardless of using live server, creating a local json for it etc. That being said I am open to any commentary/suggestions.

**Comment by narainkarthikv** [comment]
@DevyRuxpin I am learning more about this functionality. But I can see from my code that you are fetching `NmojiList.json` directly instead of fetching `fetch('./data/NmojiList.json')` as it is in the data folder. 

```plaintext
fetch('NmojiList.json')
    .then(response => {
        if (!response.ok) {
            throw new Error('Network response was not ok');
        }
        return response.json();
    })
    .then(NmojiList => {
        displayEmojis(NmojiList);
        // Use debounce to improve performance
        filterInput.addEventListener('input', debounce(() => filterEmojis(NmojiList), 250));
    })
    .catch(error => {
        console.error('Error fetching the JSON data:', error);
    });
```
try using 
```plaintext
fetch('./data/NmojiList.json')
```

Hope it resolved the issue 😊. Or if it didn't kindly ping me. We can learn it together and resolve the issue.

**Comment by DevyRuxpin** [comment]
https://github.com/DevyRuxpin/Nmoji/tree/main/nmoji

Feel free to review and test. Im going to be tied up for rest of the day but wanted to share where I am currently with it.

I have not been able to solve the local storage problem. Live Server isn't working. I even tried to replicate the code from scratch (copy paste) to force the localization and it still has issues. I keep getting error that reads: 
      
      Failed to load resource: net::ERR_CONNECTION_REFUSED localhost:8000/.data/NmojiList.json:1 
      Error fetching the JSON data:
      TypeError: Failed to fetch
      at HTMLDocument.<anonymous>

**Comment by DevyRuxpin** [comment]
https://github.com/DevyRuxpin/Nmoji

**Comment by PATILYASHH** [comment]
@narainkarthikv 

https://nmoji.vercel.app/

Check this out . I make a temporary deployment for showing the end result. If you see any issue then notify me and after all that I will remove this website from internet

**Comment by PATILYASHH** [comment]
> @narainkarthikv 
> 
> https://nmoji.vercel.app/
> 
> Check this out . I make a temporary deployment for showing the end result. If you see any issue then notify me and after all that I will remove this website from internet 

Wait , I deployed the wrong branch . I will fix it later and show you again

**Comment by narainkarthikv** [comment]
@PATILYASHH, I can see you've implemented the search option within the container. However, the current search implementation hides the emojis we need to pick, which changes our objectives. Instead, could you tweak this search into a separate container alongside the Nmoji container? Instead of search suggestions, implement a new container to show the emoji in large size with its description and tags. 

![Screenshot 2024-07-24 115734](https://github.com/user-attachments/assets/1f038afa-fd6b-43ec-b9b1-0119b7a79a7e)

**Comment by PATILYASHH** [comment]
> @PATILYASHH, I can see you've implemented the search option within the container. However, the current search implementation hides the emojis we need to pick, which changes our objectives. Instead, could you tweak this search into a separate container alongside the Nmoji container? Instead of search suggestions, implement a new container to show the emoji in large size with its description and tags. 
> 
> ![Screenshot 2024-07-24 115734](https://github.com/user-attachments/assets/1f038afa-fd6b-43ec-b9b1-0119b7a79a7e)

Got it 👍

**Comment by narainkarthikv** [comment]
> https://github.com/DevyRuxpin/Nmoji

Hi @PATILYASHH @PATILYASHH New UI/UX has been updated.

**Comment by PATILYASHH** [comment]
Okk
