### ISSUE TITLE
Feature Request: Redesign Emoji Picker Interface for Improved Usability

### ISSUE THREAD

**Issue by narainkarthikv** [narainkarthikv/Nmoji#3]
We want to enhance the user interface (UI) of the emoji picker in the Nmoji application to make it more intuitive and visually appealing. The goal is to improve how users interact with the emoji picker, making it easier and more enjoyable to use.

Tasks:

- Redesign Layout:

1. Update the layout of the emoji picker to make it more user-friendly.
2. Consider organizing emojis in a grid or other layout that improves accessibility.

- Improve Visual Design:

1. Enhance the visual design of the picker, including updating colors, fonts, and spacing to create a more polished and modern look.

- Add Hover Effects:

1. Implement hover effects on emoji items to provide visual feedback when users interact with them, such as animations or highlighting.

- Update Button Styles:

1. Improve the styles of buttons or controls within the picker to ensure they are visually consistent and easy to use.

- Enhance Tooltip Functionality:

1. Make tooltips appear quickly to provide immediate feedback about each emoji.

- Improve Copy Feedback:

1. Update the copying functionality so that when an emoji is copied, a subtle and clear message or indication shows that the emoji has been copied successfully, instead of an alert message.

- Add Picked Emoji Section:

1. Provide a separate section at the top of the picker where users can see the selected emoji in a larger size along with its description and usage.

**Comment by PATILYASHH** [comment]
Let's work on this issue, please Assign me here
