### ISSUE TITLE
Add Website to Google Search Console

### ISSUE THREAD

**Issue by PATILYASHH** [narainkarthikv/Nmoji#9]
**Description:**
This website is not added to Google Search Console, which is the reason a new user can't find it without the URL. Adding this website to Google Search Console will improve its visibility and allow users to find it more easily.

**Steps to Resolve:**
1. Sign in to Google Search Console.
2. Add the website as a property.
3. Verify ownership using one of the provided methods (HTML file upload, HTML tag, Google Analytics, Google Tag Manager, or domain name provider).
4. Submit the website’s sitemap.

**Assignee:**
Assign this task to me. I have experience with adding websites to Google Search Console and can solve this issue.

**Comment by narainkarthikv** [comment]
@PATILYASHH It is a new concept for me, and I will look into this topic to expand my knowledge further. Could you possibly share the documentation for learning Google Search Console?

**Comment by PATILYASHH** [comment]
I don't have specific learning sources for it because I learned from chatgpt . But I can explain to you

**Comment by narainkarthikv** [comment]
Will start a Discord community within this weekend or in the upcoming weeks. We can learn further together on this issue. For now, can you work on [issue #3](https://github.com/narainkarthikv/Nmoji/issues/3)?

**Comment by PATILYASHH** [comment]
> Will start a Discord community within this weekend or in the upcoming weeks. We can learn further together on this issue. For now, can you work on [issue #3](https://github.com/narainkarthikv/Nmoji/issues/3)?

oky

**Comment by PATILYASHH** [comment]
> Will start a Discord community within this weekend or in the upcoming weeks. We can learn further together on this issue. For now, can you work on [issue #3](https://github.com/narainkarthikv/Nmoji/issues/3)?
> 

I have some more plans for this project we will discuss on discord

**Comment by narainkarthikv** [comment]
> > Will start a Discord community within this weekend or in the upcoming weeks. We can learn further together on this issue. For now, can you work on [issue #3](https://github.com/narainkarthikv/Nmoji/issues/3)?
> 
> I have some more plans for this project we will discuss on discord

sure, possibly we can make the app the best

**Comment by PATILYASHH** [comment]
> > > Will start a Discord community within this weekend or in the upcoming weeks. We can learn further together on this issue. For now, can you work on [issue #3](https://github.com/narainkarthikv/Nmoji/issues/3)?
> > 
> > I have some more plans for this project we will discuss on discord
> 
> sure, possibly we can make the app the best

We will

**Comment by narainkarthikv** [comment]
> > > > Will start a Discord community within this weekend or in the upcoming weeks. We can learn further together on this issue. For now, can you work on [issue #3](https://github.com/narainkarthikv/Nmoji/issues/3)?
> > > 
> > > 
> > > I have some more plans for this project we will discuss on discord
> > 
> > 
> > sure, possibly we can make the app the best
> 
> We will make

Hey Can you also help me with my other projects too. As I started a new repo for new learners of Git, HTML, CSS, JS 
[contribution-cards](https://github.com/narainkarthikv/contribution-cards/issues/6)

**Comment by PATILYASHH** [comment]
> > > > > Will start a Discord community within this weekend or in the upcoming weeks. We can learn further together on this issue. For now, can you work on [issue #3](https://github.com/narainkarthikv/Nmoji/issues/3)?
> > > > 
> > > > 
> > > > I have some more plans for this project we will discuss on discord
> > > 
> > > 
> > > sure, possibly we can make the app the best
> > 
> > We will make
> 
> Hey Can you also help me with my other projects too. As I started a new repo for new learners of Git, HTML, CSS, JS 
> [contribution-cards](https://github.com/narainkarthikv/contribution-cards/issues/6)

Yes
